// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.8.3
//   protoc               v6.33.0
// source: ai.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "ai_pack.v1";

export interface HelloRequest {
  name: string;
}

export interface HelloReply {
  message: string;
}

export const AI_PACK_V1_PACKAGE_NAME = "ai_pack.v1";

export interface GreeterClient {
  sayHello(request: HelloRequest): Observable<HelloReply>;
}

export interface GreeterController {
  sayHello(request: HelloRequest): Promise<HelloReply> | Observable<HelloReply> | HelloReply;
}

export function GreeterControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["sayHello"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("Greeter", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("Greeter", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const GREETER_SERVICE_NAME = "Greeter";
